class LocalString {
  static const String kAppName = 'Kwality Furniture',
      kAppVersion = '1.0.0',
      forgot_pwd_header = "forgot_pwd_header",
      forgot_pwd =  "forgot_pwd",
      no_account_1 =  "no_account_1",
      no_account_2 =  "no_account_2",
      back_to_login =  "back_to_login",
      reset_pwd =  "reset_pwd",
      empty_email =  "empty_email",
      invalid_email =  "invalid_email",
      network_error =  "network_error",
      log_in =  "log_in",
      email =  "email",
      password =  "password",
      sign_in =  "sign_in",
      name =  "name",
      address =  "address",
      confirm_pwd =  "confirm_pwd",
      phone =  "phone",
      invalid_phone = "invalid_phone",
      register =  "register",
      email_address = "email_address",
      empty_pwd = "empty_pwd",
      required = "required",
      confirm_pwd_error = "confirm_pwd_error",
      first_name = "first_name",
      last_name = "last_name",
      have_account = "have_account";

}
